services:
  - type: web
    name: proxy-demo-web
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/server.js"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
