services:
  - type: web
    name: proxy-demo
    env: node
    plan: free
    region: singapore
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
